### ISSUE TITLE
Error: Column `1990` must have a unique name

### ISSUE THREAD

**Issue by gher3** [introdsci/DataScience-JennGriff#2]
https://github.com/introdsci/DataScience-JennGriff/blob/5cc35ee99ca3a567c14c7645752445939a7addcc/deliverable1.Rmd#L80

**Comment by JennGriff** [comment]
Restructured code to gather by column number rather than variable name: 
Indicators <-gather(Indicators, key = Years, "HDI_value", 6:34)
