### ISSUE TITLE
p02 peer review summary

### ISSUE THREAD

**Issue by bolson10** [introdsci/DataScience-JennGriff#5]
Data Preparation - The data provided was tidy and clean. One thing to add would be a head of the other dataset(s) acquired in phase 1, just to see where the focus started and to check its tidiness.
Modeling - The setup of the model was great, because there was many attributes used. One thing to make the model better would be to revise it by removing attributes with a high p-value.
R proficiency - The given R code was pretty good, and there was no "dead code". The comments inside the code were helpful for the documentation of the code, but some of the more elaborate code could have been described before or after the code block.
Communication - The commentary throughout is pretty good, but more introduction would have been helpful to set the stage for the deliverable.
Critical thinking- Good reasoning and insights about the data and possible implications.
Feedback- Overall I liked the content and there was some interesting insights and investigating. Revising the model will help to get more out of those insights, and could be done in the next phase.

**Comment by JennGriff** [comment]
great feedback.
Data Prep: added brief description of previous phase of project with head of the original table, and a couple of the tibbles head that were branched off that original dataframe

**Comment by JennGriff** [comment]
Modeling: added a revision of the model minus irrelevant variables, and the dimension variable that had a consistently high P value. Improved the model tremendously, Thanks!
